# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Get git hash
      id: hash
      run: echo "::set-output name=hash::$(git rev-parse --short HEAD)"
    - run: |
        cat << EOF > src/buildInfo.json
        {"date": "${{ steps.date.outputs.date }}","hash": "${{ steps.hash.outputs.hash }}"}
        EOF
    - name: Check build info
      run: |
        cat src/buildInfo.json
        cp src/buildInfo.json public/buildInfo.json
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test --if-present
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        branch: main # The branch the action should deploy to.
        folder: public # The folder the action should deploy.
        repository-name: Ozsie/ozsie.github.io
        token: ${{ secrets.DEPLOY_KEY }}
